### ISSUE TITLE
Textmate 1.5.8 Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/zen-coding#14]
```
What steps will reproduce the problem?
1. Install Zen Coding Textmate V.3
2. Install Zen CSS 1.3.1 Textmate
3. Install Zen HTML 1.3.1 Textmate
4. Type html:4s and goto menu and click "Expand Selection"

What is the expected output? What do you see instead?
I type html:4s and try to expand selection using COMMAND-E. The error that
shows up is 

Traceback (most recent call last):
  File "/tmp/temp_textmate.LhhXIw", line 29, in <module>
    doc_type = re.findall(r'\bhtml|css|xml\b', scope)[-1]
IndexError: list index out of range

What version of the product are you using? On what operating system?
Mac OS X Leopard Latest Version

Please provide any additional information below.
I am happy to bug test any updates that you need. 

```

---

Original issue reported on code.google.com by `alsha...@gmail.com` on 22 Sep 2009 at 11:10

**Comment by GoogleCodeExporter** [comment]
```
I'm also getting this error.
No matter what I enter it always outputs the error when expanding selection.
```

---

Original comment by `keo...@gmail.com` on 22 Sep 2009 at 11:15

**Comment by GoogleCodeExporter** [comment]
```
Glad I reported it then, I was hoping it was not just me. I do know textmate 
released
an update recently if that helps.


```

---

Original comment by `alsha...@gmail.com` on 22 Sep 2009 at 11:21

**Comment by GoogleCodeExporter** [comment]
```
Looks like you're trying to call Expand Abbreviation on "plain text" document. 
Try to switch to HTML or XML
```

---

Original comment by `serge....@gmail.com` on 23 Sep 2009 at 10:34

**Comment by GoogleCodeExporter** [comment]
```
I don't get the error anymore, but the text isn't expanded, it just adds a tab
(indent) on the left. (???)
```

---

Original comment by `keo...@gmail.com` on 23 Sep 2009 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
Saving the file as .html first worked, even if the file was blank.
```

---

Original comment by `alsha...@gmail.com` on 23 Sep 2009 at 4:26

**Comment by GoogleCodeExporter** [comment]
```
Not for me, that's the first thing I tested. Also, changing the language to 
HTML Zen
doesn't seem to solve the problem.
```

---

Original comment by `keo...@gmail.com` on 23 Sep 2009 at 4:28

**Comment by GoogleCodeExporter** [comment]
```
keoshi just save the file as a .html file like index.html then try it

al

```

---

Original comment by `alsha...@gmail.com` on 23 Sep 2009 at 4:30

**Comment by GoogleCodeExporter** [comment]
```
It's not necessary to save file, you just need to change coding language from 
"Plain text" to "HTML" at the bottom 
of the editor.

@keoshi: that's wierd, i'll come back to this problem a little later
```

---

Original comment by `serge....@gmail.com` on 23 Sep 2009 at 4:38

**Comment by GoogleCodeExporter** [comment]
```
Here's a little video of what happens using different settings: 
http://vimeo.com/6723051
password is 'zen'.

thanks
```

---

Original comment by `keo...@gmail.com` on 24 Sep 2009 at 11:08

**Comment by GoogleCodeExporter** [comment]
```
OK, I got the problem. I tried to make abbreviation expanding with Tab key, and 
looks like there is a bug that 
makes ZC think that you're trying to indent the selection. In order to Expand 
Abbreviation work you have to:
1. Switch language to HTML (or XML)
2. Do *not* select the text, just place cursor after the abbreviation and call 
Expand Abbreviation command

I'll fix both of these problems (error in Plain text and expanding of selected 
text) in the next version.
```

---

Original comment by `serge....@gmail.com` on 24 Sep 2009 at 11:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Yes that appears to be the exact problem
```

---

Original comment by `alsha...@gmail.com` on 24 Sep 2009 at 12:43

**Comment by GoogleCodeExporter** [comment]
```
YES, it works now! Thank you so much.
```

---

Original comment by `keo...@gmail.com` on 24 Sep 2009 at 12:58

**Comment by GoogleCodeExporter** [comment]
```
I've made a quick fix of these problems, please downlow v0.3.1 and tell me if 
it work for you.

http://zen-coding.googlecode.com/files/Zen%20Coding%20for%20TextMate%20v0.3.1.zi
p
```

---

Original comment by `serge....@gmail.com` on 24 Sep 2009 at 1:18

**Comment by GoogleCodeExporter** [comment]
```
Yup, it works. Thanks a lot!

Now I find easier just to press CMD+E when finishing the line, but it works 
both ways
so well done, appreciated.
```

---

Original comment by `keo...@gmail.com` on 25 Sep 2009 at 12:35

**Comment by GoogleCodeExporter** [comment]
```
Confirmed it is working as you stated.
```

---

Original comment by `alsha...@gmail.com` on 25 Sep 2009 at 12:46

**Comment by GoogleCodeExporter** [comment]
---

Original comment by `serge....@gmail.com` on 25 Sep 2009 at 3:20
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Unfortunately it does not work for my version of TextMate. The specs:

What steps will reproduce the problem?
1. Install Zen Coding Textmate 0.3.1
2. Install Zen CSS 1.3.1 Textmate
3. Install Zen HTML 1.3.1 Textmate
4. Type html:4s and goto menu and click "Expand Selection"

What is the expected output? What do you see instead?
I type html:4s and try to expand selection using COMMAND-E. The error that
shows up is 

Traceback (most recent call last):
  File "/tmp/temp_textmate.PDh05s", line 9, in ?
    from zencoding import zen_core
  File "/Users/intelmac01/Library/Application Support/TextMate/Pristine
Copy/Bundles/Zen Coding.tmbundle/Support/zencoding/zen_core.py", line 208
    @staticmethod
    ^
SyntaxError: invalid syntax

What version of the product are you using? On what operating system?
Mac OSX 10.4.11, TextMate 1.5.8 (Build 1509)
```

---

Original comment by `gefangen...@gmail.com` on 24 Nov 2009 at 9:50

**Comment by GoogleCodeExporter** [comment]
```
Looks like you have an old version on Python. Zen Coding requires Python 2.5+ 
in order to run. Can you upgrade 
it?
```

---

Original comment by `serge....@gmail.com` on 25 Nov 2009 at 9:56

**Comment by GoogleCodeExporter** [comment]
```
I get the same output with OS X 10.4.11 andTextMate 1.5.9 - but with Python 
2.5.4.

```

---

Original comment by `martin.b...@gmail.com` on 25 Nov 2009 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
Please try this bundle: http://zen-coding.ru/ZenCoding.tmbundle.zip
It contains newer version of Zen Coding code as well as some bugfixes
```

---

Original comment by `serge....@gmail.com` on 25 Nov 2009 at 11:02

**Comment by GoogleCodeExporter** [comment]
```
Great, that solved it.
Thanks
```

---

Original comment by `martin.b...@gmail.com` on 25 Nov 2009 at 11:10

**Comment by GoogleCodeExporter** [comment]
```
Thanks, that fixed it for me too!
```

---

Original comment by `jack...@gmail.com` on 10 May 2010 at 4:31
