### ISSUE TITLE
Error in Coda when Expanding - Plugin for Coda

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/zen-coding#215]
```
What steps will reproduce the problem?
1. Every Abbreviation I expand, same error output as below

What is the expected output? What do you see instead?

ul>li*4Traceback (most recent call last):
  File "/Users/tbinte/Library/Application Support/Coda/Plug-ins/zen.codaplugin/Contents/Resources/1B3928AC-1FDA-4956-9002-90D8C17D3B77/script", line 44, in <module>
    abbr, start_index = zen_core.find_abbr_in_line(cur_line, cur_index)
  File "/Users/tbinte/Library/Application Support/Coda/Plug-ins/zen.codaplugin/Contents/Resources/1B3928AC-1FDA-4956-9002-90D8C17D3B77/Support Files/zencoding/zen_core.py", line 157, in find_abbr_in_line
    ch = line[cur_index]
IndexError: string index out of range



What version of the product are you using? On what operating system?
Coda: 1.6.12
zen-Coding 0.6.0.1
Mac OSX 10.6.4

Please provide any additional information below.

```

---

Original issue reported on code.google.com by `tbi...@gmail.com` on 30 Oct 2010 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
Are you sure you're using the latest Zen Coding plugin? There's no such 
function in zen_core.py at line 157, and file packaging is different
```

---

Original comment by `serge....@gmail.com` on 30 Oct 2010 at 9:20

**Comment by GoogleCodeExporter** [comment]
```
Yes, there were some remnants from an old plugin. Re-Installed everything and 
works fine now. Thanks!
```

---

Original comment by `tbi...@gmail.com` on 30 Oct 2010 at 2:17

**Comment by GoogleCodeExporter** [comment]
---

Original comment by `serge....@gmail.com` on 28 Nov 2010 at 2:52
- Changed state: **Done**
