### ISSUE TITLE
Support for Geany

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/zen-coding#60]
```
Would be nice to see this also as plugin of Geany (www.geany.org). Geany has a 
plugin interface 
which should support this. If there are some features which are not available 
yet, but needed to get 
zen-coding working in Geany, I think it would be possible to accept patches, 
which provide those 
functions in the plugin interface.


```

---

Original issue reported on code.google.com by `dmaphy@googlemail.com` on 25 Nov 2009 at 11:26

**Comment by GoogleCodeExporter** [comment]
```
I'd like to see this very much too, I'm not familiar with programming languages 
used,
but if there's anything I can do to make this happen, let me know.
```

---

Original comment by `peolanha@gmail.com` on 26 Nov 2009 at 5:40

**Comment by GoogleCodeExporter** [comment]
```
Looks like Geany requires to write plugins on C
So I need help of C programmer
```

---

Original comment by `serge....@gmail.com` on 26 Nov 2009 at 9:23

**Comment by GoogleCodeExporter** [comment]
```
There is also a plan for a Python plugin interface. Anyway, for support on 
Geany and
C the developers and guys around Geany are very helpful. You may want to visit 
those
in #geany on Freenode or on their mailing lists
(http://www.geany.org/Support/MailingList) with precise questions. :)
```

---

Original comment by `dmaphy@googlemail.com` on 26 Nov 2009 at 10:24

**Comment by GoogleCodeExporter** [comment]
```
Any updates on this, is there any kind C-skilled soul able to help out? :-)
```

---

Original comment by `peolanha@gmail.com` on 29 Nov 2009 at 3:39

**Comment by GoogleCodeExporter** [comment]
```
Issue 65 has been merged into this issue.
```

---

Original comment by `serge....@gmail.com` on 30 Nov 2009 at 9:24

**Comment by GoogleCodeExporter** [comment]
```
Issue 149 has been merged into this issue.
```

---

Original comment by `serge....@gmail.com` on 3 May 2010 at 3:12

**Comment by GoogleCodeExporter** [comment]
```
I would also like to see this.
```

---

Original comment by `alyosha...@gmail.com` on 3 May 2010 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
I'm a definitive Geany addict user, so I would also like a zen-coding plugin 
for this editor !
Please please please :)
```

---

Original comment by `cont...@spheerys.fr` on 20 Jun 2010 at 2:45

**Comment by GoogleCodeExporter** [comment]
```
Same for me. I use geany since several years now and i would love to use this 
kind of plugin please :)
```

---

Original comment by `nicolas....@gmail.com` on 28 Jun 2010 at 7:57

**Comment by GoogleCodeExporter** [comment]
```
Count me in: Geany is a great editor. Over at 
http://www.geany.org/Support/PluginWishlist the developers of geany have gotten 
aware of zen coding - so maybe if you team up, developing the plugin should not 
be too much work. I'd be great to have zen coding in geany!
```

---

Original comment by `lie...@zebra.de` on 1 Aug 2010 at 5:24

**Comment by GoogleCodeExporter** [comment]
```
I'm looking to switch editor/IDE, and Geany is looking like a favourite so it 
would be great to have Zen Coding support. +1 :)
```

---

Original comment by `davidoli...@googlemail.com` on 3 Aug 2010 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
Guys, I look through Zen Coding Cheat Lists, videos and it'll be great to make 
Zen Coding support in Geany.
```

---

Original comment by `def...@gmail.com` on 7 Sep 2010 at 7:31

**Comment by GoogleCodeExporter** [comment]
```
Someone, please do this. Geany is awesome. I wish I could use zen-coding on it.
```

---

Original comment by `vikstr...@gmail.com` on 1 Dec 2010 at 6:50

**Comment by GoogleCodeExporter** [comment]
---

Original comment by `serge....@gmail.com` on 12 Dec 2010 at 3:08
- Added labels: **Type-EditorSupport**

**Comment by GoogleCodeExporter** [comment]
```
I would also like to see this. +1)
```

---

Original comment by `ZekMa...@gmail.com` on 5 Jan 2011 at 5:11

**Comment by GoogleCodeExporter** [comment]
```
Same for me, +1 :)
```

---

Original comment by `StonedDe...@gmail.com` on 5 Jan 2011 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Pretty please?
```

---

Original comment by `mako281` on 21 Jan 2011 at 3:16

**Comment by GoogleCodeExporter** [comment]
```
The request to add Zen-coding to Geany is highlighted in bold on the plugin 
wishlist; does this mean they are currently developing it ?
```

---

Original comment by `johan.bove` on 28 Jan 2011 at 10:10

**Comment by GoogleCodeExporter** [comment]
```
I'm afraid it doesn't. geany.org is running on a wiki and the Wishlist ist 
editable for everyone who may comes there. So someone who supports the wish for 
Zen Coding in Geany may has edited it and made it bold. I can not see any 
indicator in the mailing lists nor IRC at present that there is someone writing 
it.
```

---

Original comment by `dmaphy@googlemail.com` on 28 Jan 2011 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I hope someday we'll see Zen Coding support for Geany. +1
```

---

Original comment by `nervousb...@gmail.com` on 6 Feb 2011 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
Any updates on this? also i noticed that it has been stated that Geany requires 
that the plugins are written in C? Isn't zen coding written in Python? So you 
could just use CPython or some other Python in C/Python to C thingie.
```

---

Original comment by `Matias.K...@gmail.com` on 1 Mar 2011 at 6:10

**Comment by GoogleCodeExporter** [comment]
```
If a simple textarea can implement zen-coding http://zen-coding.ru/textarea/ , 
why geany wont? why?
```

---

Original comment by `sirio...@gmail.com` on 20 Mar 2011 at 10:46

**Comment by GoogleCodeExporter** [comment]
```
Because Geany still doesn’t support such simple thing for IDEs like scripting.
```

---

Original comment by `serge....@gmail.com` on 21 Mar 2011 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
Any news on this? Will it be Python or C . If it's python, i'm in. If it's C, 
I'll ask a friend. I defi-fuckinitely NEED zen-coding for geany !!
```

---

Original comment by `moebius....@gmail.com` on 23 Mar 2011 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
moebius.eye, iIt should be some sort of bridge written in C that allows editor 
to be scripted with Python
```

---

Original comment by `serge....@gmail.com` on 24 Mar 2011 at 10:19

**Comment by GoogleCodeExporter** [comment]
```
Hi people.
I think I found a temporary solution.
http://hup.hu/node/79703
And the installation instructions in Russian.
http://damour-ua.com/?p=65
```

---

Original comment by `ZekMa...@gmail.com` on 31 May 2011 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
I've made a Geany Zen Coding plugin (see the README.markdown file):
https://github.com/codebrainz/geany-zencoding

It only supports 'Expand Abbreviation' and 'Wrap with Abbreviation'.  Also, I 
have no idea if will compile on non-Linux systems.

Feedback, patches and pull requests welcome.
```

---

Original comment by `matthewb...@gmail.com` on 10 Jul 2011 at 2:52

**Comment by GoogleCodeExporter** [comment]
---

Original comment by `serge....@gmail.com` on 16 Jul 2011 at 9:52
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
Very nice. Thanks :)

I tried it on a Fedora 15 x86_64 box, and had to add a --libdir=/usr/lib64 to 
the configure script.

Everything went fine, but activating the plugin in Geany caused a crash:

$ geany -v
Geany-INFO: Geany 0.20, en_US.utf8
Geany-INFO: GTK 2.24.4, GLib 2.28.8, GIO
Geany-INFO: System data dir: /usr/share/geany
Geany-INFO: User config dir: /home/samuel/.config/geany
Geany-INFO: Added filetype Genie (51).
Geany-INFO: Loaded:   /usr/lib64/geany/splitwindow.so (Split Window)
Geany-INFO: /tmp/zc/geany-zencoding/README.markdown : None (UTF-8)
Geany-INFO: Bad color '0x0'
Geany-INFO: Bad color '0x0'
Geany-INFO: Plugin "/usr/lib64/geany/splitwindow.so" already loaded.
Geany-INFO: Found 7 plugin(s) in '/usr/lib64/geany'.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site.py", line 557, in <module>
    main()
  File "/usr/lib64/python2.7/site.py", line 540, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/lib64/python2.7/site.py", line 319, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib64/python2.7/site.py", line 192, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib64/python2.7/site.py", line 162, in addpackage
    exec line
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/abrt_exception_handler.py", line 27, in <module>
    import socket
  File "/usr/lib64/python2.7/socket.py", line 47, in <module>
    import _socket
ImportError: /usr/lib64/python2.7/lib-dynload/_socketmodule.so: undefined 
symbol: PyExc_ValueError

$ python --version
Python 2.7.1

$ geany --version
geany 0.20 (built on Feb  9 2011 with GTK 2.24.0, GLib 2.28.0, GIO)

$ uname -r
2.6.38.8-35.fc15.x86_64
```

---

Original comment by `samuelbr...@gmail.com` on 16 Jul 2011 at 11:31

**Comment by GoogleCodeExporter** [comment]
```
If you don't mind making an Issue on the GitHub page, I will look into this 
when I get some time.  Someone else from the Geany IRC channel had the exact 
same problem using Fedora.
```

---

Original comment by `matthewb...@gmail.com` on 16 Jul 2011 at 8:04

**Comment by GoogleCodeExporter** [comment]
```
I *think* I have fixed the issue on Fedora in a recent commit[1].  If anyone 
could confirm, that would be great.

[1] 
https://github.com/codebrainz/geany-zencoding/commit/170b2172b903161cb8f0aed0dcd
45c6bfbb7ae00


```

---

Original comment by `matthewb...@gmail.com` on 17 Jul 2011 at 12:46

**Comment by GoogleCodeExporter** [comment]
```
Yes, it works :) Thanks a lot!


There is however another issue (altough minor): Loading, unloading and loading 
the plugin resutls in a segfault:

Program received signal SIGSEGV, Segmentation fault.
0x00000036bd89d000 in PyType_IsSubtype () from /usr/lib64/libpython2.7.so.1.0

I don't have a debug build of Geany handy and can't provide more details. 
However, it doesn't prevent zen-coding in Geany, so it's not that bad ;)
```

---

Original comment by `samuelbr...@gmail.com` on 17 Jul 2011 at 9:33
